services:
  db:
    image: postgres:16
    container_name: yfl_db
    environment:
      POSTGRES_DB: yfl
      POSTGRES_USER: yfl_user
      POSTGRES_PASSWORD: yfl_local_password
    ports:
      - "5432:5432"
    volumes:
      - yfl_db_data:/var/lib/postgresql/data

volumes:
  yfl_db_data: